#!/usr/bin/env bash
# Save Godzilla — autonomous deploy script
# Run by cron: regenerates site, commits, PRs, merges push.
set -e

REPO_DIR="/opt/data/savegodzilla.org"
BRANCH="update/$(date +%Y%m%d)"
cd "$REPO_DIR"

# Re-authenticate gh if needed (rebuild safety)
if ! gh auth status &>/dev/null; then
  cat /opt/data/.github_token | gh auth login --with-token 2>/dev/null || true
fi

# Generate fresh content
python3 generate.py

# Create branch, commit, PR, merge
git checkout -b "$BRANCH"
git add data.json generate.py index.html about.html incidents.html press.html contact.html README.md
git commit -m "chore: daily content refresh — $(date +%B-%d-%Y)"
git push -u origin "$BRANCH"

PR_URL=$(gh pr create --base main --head "$BRANCH" \
  --title "Weekly content refresh — $(date +%B-%d-%Y)" \
  --body "Automated content rotation for savegodzilla.org.
- Incidents, testimonials, and press releases rotated weekly
- Metrics updated
- Generated by generate.py" \
  --fill)

gh pr merge "$BRANCH" --squash --delete-branch

echo "Deployed: $PR_URL"